ten_newsgroups_classes: ['business', 'entertainment', 'food', 'graphics', 'historical', 'medical', 'politics', 'space', 'sport', 'technologie']
bbcsport_classes: ['athletics', 'cricket', 'football', 'rugby', 'tennis']

ten_newsgroups_raw_texts_prefix: 'data/input/raw_texts/ten_newsgroups_texts'
bbcsport_raw_texts_prefix: 'data/input/raw_texts/bbcsport_texts'

ten_newsgroups_graphs_dataset_prefix: 'data/input/graphs_dataset/ten_newsgroups_graphs_dataset'
bbcsport_graphs_dataset_prefix: 'data/input/graphs_dataset/bbcsport_graphs_dataset'

ten_newsgroups_concept_pickles_prefix: 'data/input/concept_pickles/ten_newsgroups_graph_concepts_dataset'
bbcsport_concept_pickles_prefix: 'data/input/concept_pickles/bbcsport_graph_concepts_dataset'

ten_newsgroups_graph_concepts_dataset_prefix: 'data/output/concept_datasets/ten_newsgroups_graph_concepts_dataset'
bbcsport_graph_concepts_dataset_prefix: 'data/output/concept_datasets/bbcsport_graph_concepts_dataset'

raw_texts_csv_prefix: 'data/output/csvs'

embeddings_prefix: 'data/output/embeddings'

images_prefix: 'data/output/images'

input_checkpoints_prefix: 'data/input/checkpoints'
output_checkpoints_prefix: 'data/output/checkpoints'

graph_conv_type: 'gcn_conv'
graph_residual_connections: False

ten_newsgroups_graph_concepts: ['entertainment', 'graphics', 'historical', 'politics', 'sport']
ten_newsgroups_target_class: 'sport'

bbcsport_graph_concepts: ['cricket', 'football', 'tennis']
bbcsport_target_class: 'tennis'

min_support: 35
max_penalty: 23

diversity_method: 'none'
