CLASS_TARGET = {'coercive': 0, 'deceptive': 1, 'benign': 2}

CLASSES = list(CLASS_TARGET)

TEMPLATES = {
    'coercive': [
        {'id': 'C1', 'name': 'suspend', 'amr_frame': 'suspend-01',
         'intent': 'the account or service will be suspended unless the recipient acts'},
        {'id': 'C2', 'name': 'close', 'amr_frame': 'close-01',
         'intent': 'the account or file will be permanently closed unless the recipient acts now'},
        {'id': 'C3', 'name': 'charge', 'amr_frame': 'charge-01',
         'intent': 'a fee will be charged or their card charged unless the recipient acts'},
        {'id': 'C4', 'name': 'owe', 'amr_frame': 'owe-01',
         'intent': 'after what the sender did, the recipient owes them and must repay now'},
        {'id': 'C5', 'name': 'expire', 'amr_frame': 'expire-01',
         'intent': 'access, an offer, or an arrangement expires at a deadline'},
        {'id': 'C6', 'name': 'report', 'amr_frame': 'report-01',
         'intent': 'the sender will report the recipient to an employer or credit bureau unless they pay'},
        {'id': 'C7', 'name': 'legal', 'amr_frame': 'sue-02',
         'intent': 'legal action, arrest, or prosecution will follow unless the recipient complies'},
        {'id': 'C8', 'name': 'lose', 'amr_frame': 'lose-02',
         'intent': 'the recipient will permanently lose something unless they act'},
    ],
    'deceptive': [
        {'id': 'D1', 'name': 'win', 'amr_frame': 'win-01',
         'intent': 'the recipient has won a prize or cash in a draw'},
        {'id': 'D2', 'name': 'select', 'amr_frame': 'select-01',
         'intent': 'the recipient was selected to receive a free upgrade or bonus'},
        {'id': 'D3', 'name': 'claim', 'amr_frame': 'claim-01',
         'intent': 'the recipient must call or click to claim a reward, often a small fee first'},
        {'id': 'D4', 'name': 'verify', 'amr_frame': 'verify-01',
         'intent': 'the recipient must verify account details at a link to restore access'},
        {'id': 'D5', 'name': 'refund', 'amr_frame': 'refund-01',
         'intent': 'a refund is waiting; confirm bank or card details to receive it'},
        {'id': 'D6', 'name': 'guarantee', 'amr_frame': 'guarantee-01',
         'intent': 'a guaranteed return or guaranteed spot, risk-free'},
        {'id': 'D7', 'name': 'free', 'amr_frame': 'offer-01',
         'intent': 'a free gift, bonus, voucher, or offer is available'},
        {'id': 'D8', 'name': 'urgent', 'amr_frame': 'urge-01',
         'intent': 'act now, last chance, limited time'},
        {'id': 'D9', 'name': 'credential', 'amr_frame': 'log-01',
         'intent': 'log in, click the link, or enter your password or card details'},
    ],
    'benign': [
        {'id': 'B1', 'name': 'thank', 'amr_frame': 'thank-01',
         'intent': 'thank the recipient for something they did'},
        {'id': 'B2', 'name': 'remind', 'amr_frame': 'remind-01',
         'intent': 'remind the recipient about an upcoming event or task'},
        {'id': 'B3', 'name': 'meet', 'amr_frame': 'meet-03',
         'intent': 'arrange to meet for dinner or a review'},
        {'id': 'B4', 'name': 'ask', 'amr_frame': 'ask-02',
         'intent': 'ask the recipient to send or do something at their convenience'},
        {'id': 'B5', 'name': 'schedule', 'amr_frame': 'schedule-01',
         'intent': 'schedule a review or catch-up for a date'},
        {'id': 'B6', 'name': 'invite', 'amr_frame': 'invite-01',
         'intent': 'invite the recipient to a launch or offsite'},
        {'id': 'B7', 'name': 'inform', 'amr_frame': 'inform-01',
         'intent': 'let the recipient know about something'},
        {'id': 'B8', 'name': 'greet', 'amr_frame': 'greet-01',
         'intent': 'a greeting, good wishes, or congratulations'},
    ],
}
