ten_newsgroups_classes: ['business', 'entertainment', 'food', 'graphics', 'historical', 'medical', 'politics', 'space', 'sport', 'technologie']
bbcsport_classes: ['athletics', 'cricket', 'football', 'rugby', 'tennis']

ten_newsgroups_graphs_dataset_prefix: 'data/datasets/ten_newsgroups_graphs_dataset'
bbcsport_graphs_dataset_prefix: 'data/datasets/bbcsport_graphs_dataset'

ten_newsgroups_raw_texts_prefix: 'data/raw_data/texts/ten_newsgroups_texts'
bbcsport_raw_texts_prefix: 'data/raw_data/texts/bbcsport_texts'

raw_texts_csv_prefix: 'data/raw_data/csvs'